---
- hosts: 192.168.0.37
  become: true
  become_user: root
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present

    - name: Download Docker repository file using the get_url
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker packages (engine) using yum module
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install required Python libraries for Docker
      block:
        - name: Install Python 3 and pip
          package:
            name: python3
            state: present

        - name: Install Python libraries for Docker
          pip:
            name:
              - docker
              - requests

      become_user: "{{ ansible_ssh_user }}"
      become_method: sudo

    - name: Log into Docker Hub registry using the docker_login module
      docker_login:
        username: curtiskruse123
        password: dckr_pat_2FvrvjCvLyaJ84Tzj4pKDoeV6c0

    - name: Pull image and create the container using docker_container
      docker_container:
        name: finalcontainer
        image: curtiskruse123/finalproj
        state: started

    - name: Start the container using docker_container
      docker_container:
        name: finalcontainer
        state: started
